#!/bin/env bash

SELECTION="TOWN_1 TOWN_2 ..Quit"

echo "Wetter anzeigen in .."
select options in $SELECTION; do

	if [ "$options" = "<TOWN_1>" ]; then
		curl wttr.in/TOWN_1

	elif [ "$options" = "<TOWN_2>" ]; then
		curl wttr.in/TOWN_2

	elif [ "$options" = "..Quit" ]; then
		echo "Quit.."
		exit

	else
		clear;
		echo "please select one option"
	fi
done
