#!/bin/env bash

if [ "$1" == "--help" ]; then
	echo "wetter shows weather incl. 6 day forecast in town"
	echo "usage: wetter town"
	exit 0
fi
clear
ansiweather -l $1
ansiweather -f 6 -l $1
curl http://wttr.in/$1
